In [2]:
import numpy as np

# 3D arrays

In [10]:
M1 = np.array([[2, 4, 6], [8, 16, 32], [10, 12, 14]])
M2 = M1 / 2
l = np.array([M1, M2])
l

array([[[ 2.,  4.,  6.],
        [ 8., 16., 32.],
        [10., 12., 14.]],

       [[ 1.,  2.,  3.],
        [ 4.,  8., 16.],
        [ 5.,  6.,  7.]]])

In [14]:
np.array?

Docstring:
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.  This argument can only be used to 'upcast' the array.  For
    downcasting, use the .astype(t) method.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

In [38]:
l.sum(axis=2)

array([[12., 56., 36.],
       [ 6., 28., 18.]])

In [37]:
a = l.copy()
a[0][1][2] = 0
a

array([[[ 2.,  4.,  6.],
        [ 8., 16.,  0.],
        [10., 12., 14.]],

       [[ 1.,  2.,  3.],
        [ 4.,  8., 16.],
        [ 5.,  6.,  7.]]])

In [20]:
%timeit l[0] + 1

2.72 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
%timeit l[0:1].sum(axis=0) + 1

8.6 µs ± 989 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [39]:
a = 1
%timeit (l[0:1].sum(axis=0) + 1) if a > 1 else (l[0] + 1)

3.73 µs ± 899 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
assert (l[1] == l[1:2].sum(axis=0)).all()

# Matrix utils

In [5]:
def matrix_row_sum(M):
    assert len(M.shape) == 2
    return M.sum(axis=1)

# Set diagonals so that row sums to 1

In [6]:
# inputs
M = np.array([[0.1, 0.2, 0.4], [0.3, 0.4, 0.2], [0.1, 0.1, 0.1]])
M_start = M.copy()
# compute
diags = np.diag_indices_from(M)
M[diags] = np.ones(M.shape[0]) - matrix_row_sum(M) + np.diag(M)

# check row sums
assert np.allclose(matrix_row_sum(M), 1)
# check non-diagonal elements the same
assert np.allclose(M_start - np.diagflat(np.diag(M_start)),
                   M       - np.diagflat(np.diag(M)))
# output
print('Start')
print(M_start)
print('End')
print(M)

Start
[[0.1 0.2 0.4]
 [0.3 0.4 0.2]
 [0.1 0.1 0.1]]
End
[[0.4 0.2 0.4]
 [0.3 0.5 0.2]
 [0.1 0.1 0.8]]


# Set matrix column

In [7]:
M

array([[0.4, 0.2, 0.4],
       [0.3, 0.5, 0.2],
       [0.1, 0.1, 0.8]])

In [11]:
M[:,-1] = 0
M

array([[0.4, 0.2, 0. ],
       [0.3, 0.5, 0. ],
       [0.1, 0.1, 0. ]])

In [12]:
M[0]

array([0.4, 0.2, 0. ])

In [13]:
M[0][:-1]

array([0.4, 0.2])

# Errors

In [43]:
np.seterr(all='raise', under='ignore', divide='warn')

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

In [45]:
np.geterr()

{'divide': 'warn', 'invalid': 'raise', 'over': 'raise', 'under': 'ignore'}

In [15]:
100e-6 * 24 * 7 * 3

0.05040000000000001

In [52]:
3 / (np.float64(1) / 0)

/mnt/c/Users/Josh/Google Drive_old/Uni/Part III/project/data/env/lib/python3.4/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in double_scalars
  """Entry point for launching an IPython kernel.


0.0

In [3]:
0*np.inf

nan

# Matrix division

In [31]:
M = np.array([[2, 4, 6], [8, 16, 32], [10, 12, 14]])
v = np.array([2, 4, 8])
v = v.reshape((v.shape[0], 1))
M / v

array([[1.  , 2.  , 3.  ],
       [2.  , 4.  , 8.  ],
       [1.25, 1.5 , 1.75]])

In [22]:
v.shape

(2, 1)

In [23]:
v.T.shape

(1, 2)

In [24]:
v

array([[2],
       [4]])

In [32]:
M

array([[ 2,  4,  6],
       [ 8, 16, 32],
       [10, 12, 14]])

In [38]:
mask = (M.sum(axis=1) < 40)
M[mask,].sum(axis=1)

array([12, 36])

In [40]:
M[mask,] / M[mask,].sum(axis=1).reshape(2,1)

array([[0.16666667, 0.33333333, 0.5       ],
       [0.27777778, 0.33333333, 0.38888889]])

In [42]:
np.array([[2 /12,4/12,6/12],[10/36,12/36,14/36]])

array([[0.16666667, 0.33333333, 0.5       ],
       [0.27777778, 0.33333333, 0.38888889]])

# Updating some

In [17]:
M1 = np.array([1, -1, 0])
M2 = np.array([1,  1, 0])
def no_if(M):
    M = M.copy()
    mask = (M < 0)
    M[mask] += M.sum()
    
def with_if(M):
    M = M.copy()
    mask = (M < 0)
    if mask.any():
        M[mask] += M.sum()

In [22]:
%timeit no_if(M1)

10.5 µs ± 578 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
%timeit no_if(M2)

7.96 µs ± 4.32 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [24]:
%timeit with_if(M1)

13.2 µs ± 1.01 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [25]:
%timeit with_if(M2)

3.85 µs ± 976 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Splitting

In [39]:
a = np.array([0, 1, 2, 3, 4, 5])
b,c,d=np.split(a, 3)
b[0] = 3
a

array([3, 1, 2, 3, 4, 5])

In [3]:
np.split?

Signature: np.split(ary, indices_or_sections, axis=0)
Docstring:
Split an array into multiple sub-arrays.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

      - ary[:2]
      - ary[2:3]
      - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is returned correspondingly.
axis : int, optional
    The axis along which to split, default is 0.

Returns
-------
sub-arrays : list of ndarrays
    A list of sub-arrays.

Raises
------
ValueError
    If `indices_or_sections` is given as an integer, but
    a split does not re

# SciPy

In [8]:
from scipy.integrate import solve_ivp

In [9]:
solve_ivp?

Signature: solve_ivp(fun, t_span, y0, method='RK45', t_eval=None, dense_output=False, events=None, vectorized=False, **options)
Docstring:
Solve an initial value problem for a system of ODEs.

This function numerically integrates a system of ordinary differential
equations given an initial value::

    dy / dt = f(t, y)
    y(t0) = y0

Here t is a one-dimensional independent variable (time), y(t) is an
n-dimensional vector-valued function (state), and an n-dimensional
vector-valued function f(t, y) determines the differential equations.
The goal is to find y(t) approximately satisfying the differential
equations, given an initial value y(t0)=y0.

Some of the solvers support integration in the complex domain, but note that
for stiff ODE solvers, the right-hand side must be complex-differentiable
(satisfy Cauchy-Riemann equations [11]_). To solve a problem in the complex
domain, pass y0 with a complex data type. Another option is always to
rewrite your problem for real and imaginary part

In [13]:
output = np.ones((0,3))
a = np.array([[1, 2, 3]])
np.concatenate((output, a)).T

array([[1.],
       [2.],
       [3.]])

In [97]:
a = np.ones((3,5))
a = np.concatenate((a, np.array([[0, 0, 0]]).T),axis=1)
b = np.full((3,10), 2.0)
print(a.shape)
a = np.pad(a, ((0,0),(0,4)), 'edge')
b = np.pad(b, (0, 0), 'edge')
np.concatenate((a,b))

(3, 6)


array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [48]:
%timeit np.concatenate((np.ones((5,3)), np.array([[0, 0, 0]])))

8.15 µs ± 1.28 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [52]:
%timeit np.concatenate((np.ones((100,3)), np.array([[0, 0, 0]])))

8.97 µs ± 995 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [65]:
config = [5, 6, 7]
out=np.array([config+[i] for i in range(3)], dtype=np.double)
a=np.array([[1,2,3]])
np.concatenate((out,a.T), axis=1).shape

(3, 5)