In [2]:
import numpy as np

# Matrix utils

In [7]:
def matrix_row_sum(M):
    assert len(M.shape) == 2
    return M.sum(axis=1)

# Set diagonals so that row sums to 1

In [44]:
# inputs
M = np.array([[0.1, 0.2, 0.4], [0.3, 0.4, 0.2], [0.1, 0.1, 0.1]])
M_start = M.copy()
# compute
diags = np.diag_indices_from(M)
M[diags] = np.ones(M.shape[0]) - matrix_row_sum(M) + np.diag(M)

# check row sums
assert np.allclose(matrix_row_sum(M), 1)
# check non-diagonal elements the same
assert np.allclose(M_start - np.diagflat(np.diag(M_start)),
                   M       - np.diagflat(np.diag(M)))
# output
print('Start')
print(M_start)
print('End')
print(M)

Start
[[0.1 0.2 0.4]
 [0.3 0.4 0.2]
 [0.1 0.1 0.1]]
End
[[0.4 0.2 0.4]
 [0.3 0.5 0.2]
 [0.1 0.1 0.8]]


# Errors

In [4]:
np.seterr(all='raise', under='ignore')

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

In [5]:
np.geterr()

{'divide': 'raise', 'invalid': 'raise', 'over': 'raise', 'under': 'ignore'}

In [15]:
100e-6 * 24 * 7 * 3

0.05040000000000001