In [2]:
import numpy as np

# Matrix utils

In [7]:
def matrix_row_sum(M):
    assert len(M.shape) == 2
    return M.sum(axis=1)

# Set diagonals so that row sums to 1

In [44]:
# inputs
M = np.array([[0.1, 0.2, 0.4], [0.3, 0.4, 0.2], [0.1, 0.1, 0.1]])
M_start = M.copy()
# compute
diags = np.diag_indices_from(M)
M[diags] = np.ones(M.shape[0]) - matrix_row_sum(M) + np.diag(M)

# check row sums
assert np.allclose(matrix_row_sum(M), 1)
# check non-diagonal elements the same
assert np.allclose(M_start - np.diagflat(np.diag(M_start)),
                   M       - np.diagflat(np.diag(M)))
# output
print('Start')
print(M_start)
print('End')
print(M)

Start
[[0.1 0.2 0.4]
 [0.3 0.4 0.2]
 [0.1 0.1 0.1]]
End
[[0.4 0.2 0.4]
 [0.3 0.5 0.2]
 [0.1 0.1 0.8]]


# Errors

In [43]:
np.seterr(all='raise', under='ignore', divide='warn')

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

In [45]:
np.geterr()

{'divide': 'warn', 'invalid': 'raise', 'over': 'raise', 'under': 'ignore'}

In [15]:
100e-6 * 24 * 7 * 3

0.05040000000000001

In [52]:
3 / (np.float64(1) / 0)

/mnt/c/Users/Josh/Google Drive_old/Uni/Part III/project/data/env/lib/python3.4/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in double_scalars
  """Entry point for launching an IPython kernel.


0.0

# Matrix division

In [31]:
M = np.array([[2, 4, 6], [8, 16, 32], [10, 12, 14]])
v = np.array([2, 4, 8])
v = v.reshape((v.shape[0], 1))
M / v

array([[1.  , 2.  , 3.  ],
       [2.  , 4.  , 8.  ],
       [1.25, 1.5 , 1.75]])

In [22]:
v.shape

(2, 1)

In [23]:
v.T.shape

(1, 2)

In [24]:
v

array([[2],
       [4]])

In [32]:
M

array([[ 2,  4,  6],
       [ 8, 16, 32],
       [10, 12, 14]])

In [38]:
mask = (M.sum(axis=1) < 40)
M[mask,].sum(axis=1)

array([12, 36])

In [40]:
M[mask,] / M[mask,].sum(axis=1).reshape(2,1)

array([[0.16666667, 0.33333333, 0.5       ],
       [0.27777778, 0.33333333, 0.38888889]])

In [42]:
np.array([[2 /12,4/12,6/12],[10/36,12/36,14/36]])

array([[0.16666667, 0.33333333, 0.5       ],
       [0.27777778, 0.33333333, 0.38888889]])